# 065. Promise catch 사용하기

#### **_학습목표 : Propmise catch 함수의 사용 방법을 이해_**

####  **_Propmise catch 함수의 특징과 기능을 확인_** 

-   Promise의 상태가 대기, 이행, 거부 중 거부 상태가 됐을 때 catch 함수를 실행. 대기 상태의 Promise에 에러가 발생해 이행으로 상태 변화를 하지 못하는 경우

-   App.js 수정

```js

import React from "react";
import Promise from "./R065_Promise"

function App() {
  return (
    <div>
      <h1>Start React 200!</h1>
      <Promise />
    </div>
  );
}

export default App;



```

  
  
  

-   R065_Promise.js 파일 임포트  
      
      
      
    

```js

import React, { Component } from "react";

class R065_Promise extends Component {
  componentDidMount() {
    new Promise((resolve, reject) => {
      reject(Error("Error Info"));
    })
      .then(result => console.log("then" + result))
      .catch(result => console.log("catch" + result));
  }

  render() {
    return <h1>Promise</h1>;
  }
}

export default R065_Promise;

```

  
  

-   Promise라는 객체를 생성해 promise를 사용함. 파라미터로 2개의 함수를 받으면 첫 번째 함수(resolve)는 이행 함수, 두번째 함수(reject)는 거부 함수로 사용
-   거부 함수 reject를 실행하면서 Error 객체를 사용해 에러를 발생
-   promise 동작중 거부 함수가 실행되면, 이행 상태가 되지 못하기 때문에 then 함수는 실행되지 않음
-   promise의 상태로 거부로 변하면서 catch 함수가 실행. reject 함수에서 파라미터로 전달받은 에러 정보를 출력

> 
> 
> 